name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      # Chrome 설치 (Selenium용)
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      # Secrets → 환경변수로 노출
      - name: Export env
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "API_BASE=${{ secrets.API_BASE }}" >> $GITHUB_ENV
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> $GITHUB_ENV

      # 테스트 실행 (현재 디렉토리 구조에 맞춰 경로 지정)
      - name: Run pytest (api + ui)
        run: pytest -q api_test ui_test

      # Allure raw 결과 업로드
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      # Allure HTML 생성 & 업로드(선택이지만 추천)
      - name: Generate Allure HTML
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: reports/allure-results
          report_path: reports/allure-report
          keep_reports: 10

      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html
          path: reports/allure-report
